timeout: 3
interface_resolution: 1280x800

backdrop: 1a2b3c
term_background: 802a3b4c
term_foreground: ffffff
term_wallpaper: boot():/boot/limine/boo.png
wallpaper: boot():/boot/limine/boo.png

/AvoryOS
    protocol: limine
    path: boot():/boot/kernel
    module_path: boot():/disk.img
    module_string: disk.img
    resolution: 1280x800