#!/bin/sh
set -eu

cmd=${0##*/}
usage() { echo "usage: $cmd [options] name" >&2; exit 2; }

case "$cmd" in
useradd)
    home= shell=/bin/bash uid= primary= groups= gecos= create_home=1
    while [ $# -gt 0 ]; do
        case "$1" in
            -m) create_home=1; shift ;;
            -M) create_home=0; shift ;;
            -u) [ $# -ge 2 ] || usage; uid=$2; shift 2 ;;
            -g) [ $# -ge 2 ] || usage; primary=$2; shift 2 ;;
            -G) [ $# -ge 2 ] || usage; groups=$2; shift 2 ;;
            -d) [ $# -ge 2 ] || usage; home=$2; shift 2 ;;
            -s) [ $# -ge 2 ] || usage; shell=$2; shift 2 ;;
            -c) [ $# -ge 2 ] || usage; gecos=$2; shift 2 ;;
            --) shift; break ;;
            -*) usage ;;
            *) break ;;
        esac
    done
    [ $# -eq 1 ] || usage; name=$1
    [ -n "$home" ] || home=/home/$name
    set -- -D -h "$home" -s "$shell" -g "$gecos"
    [ -z "$uid" ] || set -- "$@" -u "$uid"
    [ -z "$primary" ] || set -- "$@" -G "$primary"
    [ "$create_home" -eq 1 ] || set -- "$@" -H
    /usr/sbin/adduser "$@" "$name"
    sed -i -E "s/^($name):[^:]*:/\1:!:/" /etc/passwd
    rm -f /etc/shadow /etc/shadow- /etc/gshadow /etc/gshadow-
    if [ "$create_home" -eq 1 ]; then
        mkdir -p "$home"; cp -a /etc/skel/. "$home"/ 2>/dev/null || true
        chown -R "$name" "$home"; chmod 0700 "$home"
    fi
    oldifs=$IFS; IFS=,
    for group in $groups; do [ -z "$group" ] || /usr/sbin/addgroup "$name" "$group"; done
    IFS=$oldifs
    ;;
userdel)
    remove=0
    [ "${1:-}" != "-r" ] || { remove=1; shift; }
    [ $# -eq 1 ] || usage
    [ "$remove" -eq 0 ] && exec /usr/sbin/deluser "$1"
    exec /usr/sbin/deluser --remove-home "$1"
    ;;
groupadd)
    gid=
    if [ "${1:-}" = "-g" ]; then [ $# -ge 3 ] || usage; gid=$2; shift 2; fi
    [ $# -eq 1 ] || usage
    [ -z "$gid" ] && exec /usr/sbin/addgroup "$1"
    exec /usr/sbin/addgroup -g "$gid" "$1"
    ;;
groupdel)
    [ $# -eq 1 ] || usage; exec /usr/sbin/delgroup "$1"
    ;;
usermod)
    append=0; groups=; lock=; shell=; home=
    while [ $# -gt 0 ]; do
        case "$1" in
            -a) append=1; shift ;;
            -G) [ $# -ge 2 ] || usage; groups=$2; shift 2 ;;
            -aG) [ $# -ge 2 ] || usage; append=1; groups=$2; shift 2 ;;
            -L) lock=1; shift ;;
            -U) lock=0; shift ;;
            -s) [ $# -ge 2 ] || usage; shell=$2; shift 2 ;;
            -d) [ $# -ge 2 ] || usage; home=$2; shift 2 ;;
            *) break ;;
        esac
    done
    [ $# -eq 1 ] || usage; name=$1
    [ "$append" -eq 1 ] || [ -z "$groups" ] || { echo "usermod: replacing group lists is not supported" >&2; exit 2; }
    oldifs=$IFS; IFS=,
    for group in $groups; do [ -z "$group" ] || /usr/sbin/addgroup "$name" "$group"; done
    IFS=$oldifs
    [ -z "$lock" ] || { [ "$lock" -eq 1 ] && passwd -l "$name" || passwd -u "$name"; }
    [ -z "$shell" ] || sed -i -E "s#^($name:[^:]*:[^:]*:[^:]*:[^:]*:[^:]*:).*#\1$shell#" /etc/passwd
    [ -z "$home" ] || sed -i -E "s#^($name:[^:]*:[^:]*:[^:]*:[^:]*:)[^:]*:#\1$home:#" /etc/passwd
    ;;
groupmod)
    newname=; gid=
    while [ $# -gt 0 ]; do
        case "$1" in
            -n) [ $# -ge 2 ] || usage; newname=$2; shift 2 ;;
            -g) [ $# -ge 2 ] || usage; gid=$2; shift 2 ;;
            *) break ;;
        esac
    done
    [ $# -eq 1 ] || usage; name=$1
    [ -z "$newname" ] || sed -i -E "s/^$name:/$newname:/" /etc/group
    [ -z "$gid" ] || sed -i -E "s/^($name:[^:]*:)[0-9]+:/\1$gid:/" /etc/group
    ;;
*) usage ;;
esac
