/*
 * wl_client_test.c — Minimal Wayland client for AscentOS
 *
 * Connects to tinywl, creates an xdg_toplevel, and draws an animated
 * colour pattern using wl_shm.  No external libs beyond libwayland-client.
 *
 * Each frame cycles the hue so you can see it's actually running.
 */

#include <errno.h>
#include <fcntl.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <wayland-client-core.h>
#include <wayland-client-protocol.h>

#include "xdg-shell-client-protocol.h"   /* generated by wayland-scanner client-header */

/* ── frame dimensions ────────────────────────────────────────────────────── */
#define WIDTH  640
#define HEIGHT 480
#define STRIDE (WIDTH * 4)
#define SIZE   (STRIDE * HEIGHT)

/* ── state ───────────────────────────────────────────────────────────────── */
static struct wl_display    *display;
static struct wl_registry   *registry;
static struct wl_compositor *compositor;
static struct wl_shm        *shm;
static struct xdg_wm_base   *xdg_wm_base;

static struct wl_surface    *surface;
static struct xdg_surface   *xdg_surface;
static struct xdg_toplevel  *xdg_toplevel;

static struct wl_shm_pool   *pool;
static struct wl_buffer     *buffer;
static uint32_t             *pixels;   /* mmap'd shm region */

static int running = 1;
static int configured = 0;
static int frame_count = 0;

/* ── helpers ─────────────────────────────────────────────────────────────── */

/* Create an anonymous shared memory file. */
static int create_shm_file(size_t size) {
    /* Try memfd_create first (Linux 3.17+) */
    int fd = -1;

#ifdef __NR_memfd_create
    fd = syscall(__NR_memfd_create, "wl_shm", 0);
#endif

    if (fd < 0) {
        /* Fallback: open a temp file and unlink it */
        char path[] = "/tmp/wl-shm-XXXXXX";
        fd = mkstemp(path);
        if (fd < 0) { perror("mkstemp"); return -1; }
        unlink(path);
    }

    if (ftruncate(fd, (off_t)size) < 0) {
        perror("ftruncate");
        close(fd);
        return -1;
    }
    return fd;
}

/* HSV → ARGB32.  h in [0,360), s/v in [0,1]. */
static uint32_t hsv_to_argb(float h, float s, float v) {
    float c  = v * s;
    float x  = c * (1.0f - (float)__builtin_fabs(__builtin_fmodf(h / 60.0f, 2.0f) - 1.0f));
    float m  = v - c;
    float r, g, b;
    if      (h <  60) { r=c; g=x; b=0; }
    else if (h < 120) { r=x; g=c; b=0; }
    else if (h < 180) { r=0; g=c; b=x; }
    else if (h < 240) { r=0; g=x; b=c; }
    else if (h < 300) { r=x; g=0; b=c; }
    else              { r=c; g=0; b=x; }
    uint8_t R = (uint8_t)((r + m) * 255);
    uint8_t G = (uint8_t)((g + m) * 255);
    uint8_t B = (uint8_t)((b + m) * 255);
    return (uint32_t)(0xFF000000 | (R << 16) | (G << 8) | B);
}

/* Paint a frame: rotating hue wheel with frame_count offset. */
static void paint_frame(void) {
    float hue_offset = (float)(frame_count % 360);
    for (int y = 0; y < HEIGHT; y++) {
        for (int x = 0; x < WIDTH; x++) {
            float hue = __builtin_fmodf(
                hue_offset + (float)x * 360.0f / WIDTH + (float)y * 0.1f,
                360.0f);
            float val = 0.5f + 0.5f * (float)y / HEIGHT;
            pixels[y * WIDTH + x] = hsv_to_argb(hue, 1.0f, val);
        }
    }
    frame_count += 3;   /* advance hue each frame */
}

/* ── xdg_wm_base listener ─────────────────────────────────────────────────── */

static void xdg_wm_base_ping(void *data, struct xdg_wm_base *base,
                              uint32_t serial) {
    (void)data;
    xdg_wm_base_pong(base, serial);
}

static const struct xdg_wm_base_listener xdg_wm_base_listener = {
    .ping = xdg_wm_base_ping,
};

/* ── xdg_surface listener ─────────────────────────────────────────────────── */

static void xdg_surface_configure(void *data, struct xdg_surface *surf,
                                  uint32_t serial) {
    (void)data;
    xdg_surface_ack_configure(surf, serial);
    configured = 1;
}

static const struct xdg_surface_listener xdg_surface_listener = {
    .configure = xdg_surface_configure,
};

/* ── xdg_toplevel listener ────────────────────────────────────────────────── */

static void xdg_toplevel_configure(void *data, struct xdg_toplevel *tl,
                                   int32_t width, int32_t height,
                                   struct wl_array *states) {
    (void)data; (void)tl; (void)width; (void)height; (void)states;
    /* We ignore resize requests — fixed 640×480 for simplicity */
}

static void xdg_toplevel_close(void *data, struct xdg_toplevel *tl) {
    (void)data; (void)tl;
    running = 0;
}

static void xdg_toplevel_configure_bounds(void *data, struct xdg_toplevel *tl,
                                          int32_t width, int32_t height) {
    (void)data; (void)tl; (void)width; (void)height;
}

static void xdg_toplevel_wm_capabilities(void *data, struct xdg_toplevel *tl,
                                         struct wl_array *caps) {
    (void)data; (void)tl; (void)caps;
}

static const struct xdg_toplevel_listener xdg_toplevel_listener = {
    .configure        = xdg_toplevel_configure,
    .close            = xdg_toplevel_close,
    .configure_bounds = xdg_toplevel_configure_bounds,
    .wm_capabilities  = xdg_toplevel_wm_capabilities,
};

/* ── frame callback ───────────────────────────────────────────────────────── */

static void frame_done(void *data, struct wl_callback *cb, uint32_t time);

static const struct wl_callback_listener frame_listener = {
    .done = frame_done,
};

static void request_frame(void) {
    struct wl_callback *cb = wl_surface_frame(surface);
    wl_callback_add_listener(cb, &frame_listener, NULL);
    paint_frame();
    wl_surface_attach(surface, buffer, 0, 0);
    wl_surface_damage_buffer(surface, 0, 0, WIDTH, HEIGHT);
    wl_surface_commit(surface);
}

static void frame_done(void *data, struct wl_callback *cb, uint32_t time) {
    (void)data; (void)time;
    wl_callback_destroy(cb);
    if (running) request_frame();
}

/* ── wl_registry listener ─────────────────────────────────────────────────── */

static void registry_global(void *data, struct wl_registry *reg,
                             uint32_t name, const char *iface,
                             uint32_t version) {
    (void)data;
    if (strcmp(iface, wl_compositor_interface.name) == 0) {
        compositor = wl_registry_bind(reg, name, &wl_compositor_interface,
                                      version < 5 ? version : 5);
    } else if (strcmp(iface, wl_shm_interface.name) == 0) {
        shm = wl_registry_bind(reg, name, &wl_shm_interface, 1);
    } else if (strcmp(iface, xdg_wm_base_interface.name) == 0) {
        xdg_wm_base = wl_registry_bind(reg, name, &xdg_wm_base_interface,
                                       version < 3 ? version : 3);
        xdg_wm_base_add_listener(xdg_wm_base, &xdg_wm_base_listener, NULL);
    }
}

static void registry_global_remove(void *data, struct wl_registry *reg,
                                   uint32_t name) {
    (void)data; (void)reg; (void)name;
}

static const struct wl_registry_listener registry_listener = {
    .global        = registry_global,
    .global_remove = registry_global_remove,
};

/* ── main ─────────────────────────────────────────────────────────────────── */

int main(void) {
    printf("[wl_client] connecting to Wayland compositor...\n");

    display = wl_display_connect(NULL);
    if (!display) {
        fprintf(stderr, "[wl_client] wl_display_connect failed "
                        "(is WAYLAND_DISPLAY set?)\n");
        return 1;
    }
    printf("[wl_client] connected\n");

    registry = wl_display_get_registry(display);
    wl_registry_add_listener(registry, &registry_listener, NULL);
    wl_display_roundtrip(display);   /* discover globals */

    if (!compositor || !shm || !xdg_wm_base) {
        fprintf(stderr, "[wl_client] missing required globals "
                        "(compositor=%p shm=%p xdg_wm_base=%p)\n",
                (void *)compositor, (void *)shm, (void *)xdg_wm_base);
        return 1;
    }
    printf("[wl_client] globals found\n");

    /* Create shared memory buffer */
    int fd = create_shm_file(SIZE);
    if (fd < 0) return 1;

    pixels = mmap(NULL, SIZE, PROT_READ | PROT_WRITE, MAP_SHARED, fd, 0);
    if (pixels == MAP_FAILED) { perror("mmap"); return 1; }

    pool   = wl_shm_create_pool(shm, fd, SIZE);
    buffer = wl_shm_pool_create_buffer(pool, 0, WIDTH, HEIGHT, STRIDE,
                                       WL_SHM_FORMAT_XRGB8888);
    wl_shm_pool_destroy(pool);
    close(fd);

    /* Create surface and xdg_toplevel */
    surface     = wl_compositor_create_surface(compositor);
    xdg_surface = xdg_wm_base_get_xdg_surface(xdg_wm_base, surface);
    xdg_surface_add_listener(xdg_surface, &xdg_surface_listener, NULL);

    xdg_toplevel = xdg_surface_get_toplevel(xdg_surface);
    xdg_toplevel_add_listener(xdg_toplevel, &xdg_toplevel_listener, NULL);
    xdg_toplevel_set_title(xdg_toplevel, "AscentOS Wayland Client");

    /* Commit empty surface to trigger configure */
    wl_surface_commit(surface);
    wl_display_roundtrip(display);   /* wait for configure */

    if (!configured) {
        fprintf(stderr, "[wl_client] no configure received\n");
        return 1;
    }
    printf("[wl_client] configured — starting render loop\n");

    /* Kick off frame loop */
    request_frame();

    while (running && wl_display_dispatch(display) != -1)
        ;

    printf("[wl_client] exiting after %d frames\n", frame_count);
    xdg_toplevel_destroy(xdg_toplevel);
    xdg_surface_destroy(xdg_surface);
    wl_surface_destroy(surface);
    wl_buffer_destroy(buffer);
    munmap(pixels, SIZE);
    wl_display_disconnect(display);
    return 0;
}
